#!/usr/bin/env ruby
#
# This is just a little helper script to send an external request to Kari.app

if ARGV[0].nil?
  puts 'This utility will open Kari.app and perform the search for the keyword specified.', "Usage: #{$0} keyword"
else
  system '/usr/bin/osascript -e "tell application \"Kari\" to activate"'

  require "osx/foundation"
  OSX::NSDistributedNotificationCenter.defaultCenter.objc_send(
    :postNotificationName, 'KariOpenDocumentation',
                  :object, 'KariCommandLineHelper',
                :userInfo, { 'query' => ARGV[0] }
  )
end